# Dataset - US

In [1]:
import pandas as pd

## Initialize

In [2]:
srcUS = "./time_series_covid19_confirmed_US.csv"
dest = "./time_series_covid19_confirmed_US_transformed.csv"
stateCoordinates = {
    "Wisconsin": (44.500000, -89.500000),
    "West Virginia": (39.000000, -80.500000),
    "Vermont": (44.000000, -72.699997),
    "Texas": (31.000000, -100.000000),
    "South Dakota": (44.500000, -100.000000),
    "Rhode Island": (41.700001, -71.500000),
    "Oregon": (44.000000, -120.500000),
    "New York": (43.000000, -75.000000),
    "New Hampshire": (44.000000, -71.500000),
    "Nebraska": (41.500000, -100.000000),
    "Kansas": (38.500000, -98.000000),
    "Mississippi": (33.000000, -90.000000),
    "Illinois": (40.000000, -89.000000),
    "Delaware": (39.000000, -75.500000),
    "Connecticut": (41.599998, -72.699997),
    "Arkansas": (34.799999, -92.199997),
    "Indiana": (40.273502, -86.126976),
    "Missouri": (38.573936, -92.603760),
    "Florida": (27.994402, -81.760254),
    "Nevada": (39.876019, -117.224121),
    "Maine": (45.367584, -68.972168),
    "Michigan": (44.182205, -84.506836),
    "Georgia": (33.247875, -83.441162),
    "Hawaii": (19.741755, -155.844437),
    "Alaska": (66.160507, -153.369141),
    "Tennessee": (35.860119, -86.660156),
    "Virginia": (37.926868, -78.024902),
    "New Jersey": (39.833851, -74.871826),
    "Kentucky": (37.839333, -84.270020),
    "North Dakota": (47.650589, -100.437012),
    "Minnesota": (46.392410, -94.636230),
    "Oklahoma": (36.084621, -96.921387),
    "Montana": (46.965260, -109.533691),
    "Washington": (47.751076, -120.740135),
    "Utah": (39.419220, -111.950684),
    "Colorado": (39.113014, -105.358887),
    "Ohio": (40.367474, -82.996216),
    "Alabama": (32.318230, -86.902298),
    "Iowa": (42.032974, -93.581543),
    "New Mexico": (34.307144, -106.018066),
    "South Carolina": (33.836082, -81.163727),
    "Pennsylvania": (41.203323, -77.194527),
    "Arizona": (34.048927, -111.093735),
    "Maryland": (39.045753, -76.641273),
    "Massachusetts": (42.407211, -71.382439),
    "California": (36.778259, -119.417931),
    "Idaho": (44.068203, -114.742043),
    "Wyoming": (43.075970, -107.290283),
    "North Carolina": (35.782169, -80.793457),
    "Louisiana": (30.391830, -92.329102)
}

# Read data
usDf = pd.read_csv(srcUS)
usDf.head(20)

,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country_Region,Lat,Long_,...,10/2/20,10/3/20,10/4/20,10/5/20,10/6/20,10/7/20,10/8/20,10/9/20,10/10/20,10/11/20
0,84001001,US,USA,840,1001.0,Autauga,Alabama,US,32.539527,-86.644082,...,1805,1818,1828,1831,1839,1852,1863,1882,1898,1905
1,84001003,US,USA,840,1003.0,Baldwin,Alabama,US,30.727750,-87.722071,...,6024,6048,6073,6085,6116,6134,6141,6172,6190,6203
2,84001005,US,USA,840,1005.0,Barbour,Alabama,US,31.868263,-85.387129,...,902,921,921,921,923,927,927,939,942,942
3,84001007,US,USA,840,1007.0,Bibb,Alabama,US,32.996421,-87.125115,...,675,678,686,687,691,703,708,719,726,736
4,84001009,US,USA,840,1009.0,Blount,Alabama,US,33.982109,-86.567906,...,1642,1655,1656,1662,1665,1673,1681,1689,1704,1713
5,84001011,US,USA,840,1011.0,Bullock,Alabama,US,32.100305,-85.712655,...,612,613,613,613,616,618,619,622,623,624
6,84001013,US,USA,840,1013.0,Butler,Alabama,US,31.753001,-86.680575,...,922,924,926,927,928,933,932,943,952,958
7,84001015,US,USA,840,1015.0,Calhoun,Alabama,US,33.774837,-85.826304,...,3628,3660,3679,3705,3730,3743,3752,3803,3823,3841
8,84001017,US,USA,840,1017.0,Chambers,Alabama,US,32.913601,-85.390727,...,1185,1204,1205,1208,1210,1211,1222,1238,1242,1242
9,84001019,US,USA,840,1019.0,Cherokee,Alabama,US,34.178060,-85.606390,...,631,639,639,642,644,651,654,662,666,670
10,84001021,US,USA,840,1021.0,Chilton,Alabama,US,32.850441,-86.717326,...,1624,1640,1648,1661,1672,1679,1684,1701,1713,1722
11,84001023,US,USA,840,1023.0,Choctaw,Alabama,US,32.022273,-88.265644,...,359,361,366,366,367,368,369,374,375,376
12,84001025,US,USA,840,1025.0,Clarke,Alabama,US,31.680999,-87.835486,...,1129,1143,1156,1158,1158,1166,1184,1203,1216,1219
13,84001027,US,USA,840,1027.0,Clay,Alabama,US,33.269842,-85.858361,...,600,608,611,613,614,623,627,634,641,646
14,84001029,US,USA,840,1029.0,Cleburne,Alabama,US,33.676792,-85.520059,...,420,424,427,428,436,448,449,452,467,468
15,84001031,US,USA,840,1031.0,Coffee,Alabama,US,31.399328,-85.989010,...,1404,1452,1462,1472,1482,1486,1497,1513,1521,1532
16,84001033,US,USA,840,1033.0,Colbert,Alabama,US,34.698475,-87.801685,...,1707,1722,1734,1744,1755,1765,1771,1787,1804,1813
17,84001035,US,USA,840,1035.0,Conecuh,Alabama,US,31.434017,-86.993200,...,539,540,540,540,540,540,542,546,547,547
18,84001037,US,USA,840,1037.0,Coosa,Alabama,US,32.936901,-86.248477,...,175,179,179,179,179,180,183,186,187,187
19,84001039,US,USA,840,1039.0,Covington,Alabama,US,31.247785,-86.450509,...,1441,1477,1478,1480,1486,1495,1514,1533,1541,1561

## Data Manipulation

In [3]:
# Drop unwanted columns
droppedCols = [0, 1, 2, 3, 4, 5, 10]
usDf = usDf.iloc[:, [col for col in range(len(usDf.columns)) if col not in droppedCols]]

# Rename columns (inplace)
usDf.rename(columns = {
    "Long_": "Long"
}, inplace = True)

# Group separately and combine
#   - 1. Group Lat and Long (aggregated by taking mean)
#   - 2. Group Confirmed Cases (aggregated by taking sum)
firstHalf = usDf.iloc[:, :4].groupby(["Province_State", "Country_Region"]).first().reset_index()
secondHalf = usDf.drop(usDf.columns[[2, 3]], axis = 1).groupby(["Province_State", "Country_Region"]).sum().reset_index()
usDf = pd.concat([firstHalf, secondHalf.iloc[:, 2:]], axis = 1)

# Drop regions that are not in dictionary (stateCoordinates)
usDf = usDf[usDf["Province_State"].isin(stateCoordinates)]

# Update "Lat" and "Long"
for index, row in usDf.iterrows():
    if row["Province_State"] in stateCoordinates:
        usDf.at[index, "Lat"] = stateCoordinates[row["Province_State"]][0]
        usDf.at[index, "Long"] = stateCoordinates[row["Province_State"]][1]
        
# Derive confirmed cases per day and attach back to the source dataframe
locationsDf = usDf.iloc[:, :4]
datesDf = usDf.iloc[:, 4:].diff(axis = 1)
diffDf = pd.concat([locationsDf, datesDf], axis = 1)

# Transform spreading "date & confirmed cases" data into "Date" adn "Confirmed Cases"
usDf = diffDf.melt(
    id_vars = ["Province_State", "Country_Region", "Lat", "Long"],
    var_name = "Date",
    value_name = "Confirmed Cases")

In [4]:
usDf

,Province_State,Country_Region,Lat,Long,Date,Confirmed Cases
0,Alabama,US,32.318230,-86.902298,1/22/20,NaN
1,Alaska,US,66.160507,-153.369141,1/22/20,NaN
2,Arizona,US,34.048927,-111.093735,1/22/20,NaN
3,Arkansas,US,34.799999,-92.199997,1/22/20,NaN
4,California,US,36.778259,-119.417931,1/22/20,NaN
...,...,...,...,...,...,...
13195,Virginia,US,37.926868,-78.024902,10/11/20,800.0
13196,Washington,US,47.751076,-120.740135,10/11/20,0.0
13197,West Virginia,US,39.000000,-80.500000,10/11/20,205.0
13198,Wisconsin,US,44.500000,-89.500000,10/11/20,2676.0
13199,Wyoming,US,43.075970,-107.290283,10/11/20,156.0

In [5]:
# Save transformed dataset
usDf.to_csv(dest, index = False)